### GET Patients

GET http://localhost:8000/api/patients

### GET Patient by DNI 

GET http://localhost:8000/api/patients/dni/23456789

### GET Patients by Social Security

GET http://localhost:8000/api/patients/social-security/swiss

### POST Create Patient

POST http://localhost:8000/api/patients
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "dni": "40128092",
  "email": "john@gmail.com",
  "phoneNumber": "1234567890",
  "socialSecurity": "Swiss Medical",
  "memberNumber": "1234567851",
   "birthDate": "1990-01-01"
}

### PUT Update Patient

PUT http://localhost:8000/api/patients/1
Content-Type: application/json

{
  "firstName": "Albert",
  "lastName": "Doe",
  "dni": "40128095",
  "email": "john123@gmail.com",
  "phoneNumber": "1234567890",
  "socialSecurity": "Swiss Medical"
}

### DELETE Patient

DELETE http://localhost:8000/api/patients/1
