### GET pacientes
GET http://localhost:8080/pacientes
Accept: application/json

### POST pacientes
POST http://localhost:8080/pacientes
Content-Type: application/json

{
    "dni": "86754321",
    "nombre": "Nicolas",
    "apellido": "Berti",
    "obraSocial": "OSDE",
    "email": "nicolas.berti@teamcubation.com",
    "telefono": "123456798"
}

### GET paciente by dni: 86754321
GET http://localhost:8080/pacientes/86754321

### POST pacientes incorrecto. deberia dar error.
POST http://localhost:8080/pacientes
Content-Type: application/json

{
  "apellido": "1111",
  "nombre": "Nicolas"
}

### PUT pacientes
PUT http://localhost:8080/pacientes/111111
Content-Type: application/json

{
    "nombre": "Martin",
    "apellido": "Girolamo",
    "email": "nicolas.berti69@gmail.com"
}

### GET paciente by 111111
GET http://localhost:8080/pacientes/111111

### GET paciente by NAME
GET http://localhost:8080/pacientes/nombre/Martin

### GET paciente by obra social
GET http://localhost:8080/pacientes/obra_social?obraSocial=OSDE&page=1&size=10

### GET paciente by DNI with SP
GET http://localhost:8080/pacientes/dni/90123456

### GET paciente by DNI
GET http://localhost:8080/pacientes/90123456

### GET paciente by DNI with SP
GET http://localhost:8080/pacientes/dni/1

### GET paciente by DNI
GET http://localhost:8080/pacientes/1

### GET paciente by nombre with SP
GET http://localhost:8080/pacientes/nombre/Laura

### GET paciente by obra social with SP
GET http://localhost:8080/pacientes/obra_social?obraSocial=OSDE&page=1&size=2